export const SKILL_ICONS = {
  Attack: "/icons/Attack_icon.png",
  Strength: "/icons/Strength_icon.png",
  Defence: "/icons/Defence_icon.png",
  Ranged: "/icons/Ranged_icon.png",
  Prayer: "/icons/Prayer_icon.png",
  Magic: "/icons/Magic_icon.png",
  Runecraft: "/icons/Runecraft_icon.png",
  Construction: "/icons/Construction_icon.png",
  Hitpoints: "/icons/Hitpoints_icon.png",
  Agility: "/icons/Agility_icon.png",
  Herblore: "/icons/Herblore_icon.png",
  Thieving: "/icons/Thieving_icon.png",
  Crafting: "/icons/Crafting_icon.png",
  Fletching: "/icons/Fletching_icon.png",
  Slayer: "/icons/Slayer_icon.png",
  Hunter: "/icons/Hunter_icon.png",
  Mining: "/icons/Mining_icon.png",
  Smithing: "/icons/Smithing_icon.png",
  Fishing: "/icons/Fishing_icon.png",
  Cooking: "/icons/Cooking_icon.png",
  Firemaking: "/icons/Firemaking_icon.png",
  Woodcutting: "/icons/Woodcutting_icon.png",
  Farming: "/icons/Farming_icon.png",
  Sailing: "/icons/Sailing_icon.png",
};
